import nextPlugin from "eslint-config-next";

export default [
  ...nextPlugin,
  {
    /**
     * Vendored registry code (shadcn `@animate-ui` primitives and the hooks they
     * pull in). These files are generated by `npx shadcn add` and are rewritten
     * verbatim on the next install, so any fix made here would be silently lost —
     * the design-system brief marks them "do not edit" for that reason.
     *
     * They trip the React Compiler rules (`setState` inside an effect, refs read
     * during render). Our own components are still checked; only the generated
     * files are exempt.
     */
    files: [
      "src/components/animate-ui/**",
      "src/hooks/use-auto-height.tsx",
      "src/hooks/use-controlled-state.tsx",
      "src/hooks/use-data-state.tsx",
      "src/hooks/use-is-in-view.tsx",
      "src/lib/get-strict-context.tsx",
    ],
    rules: {
      "react-hooks/set-state-in-effect": "off",
      "react-hooks/refs": "off",
      "react-hooks/component-hook-factories": "off",
      "react-hooks/globals": "off",
      "react-hooks/immutability": "off",
      "react-hooks/preserve-manual-memoization": "off",
      "react-hooks/purity": "off",
      "react-hooks/static-components": "off",
      "react-hooks/error-boundaries": "off",
      "react-hooks/use-memo": "off",
      "react-hooks/set-state-in-render": "off",
      "@typescript-eslint/no-explicit-any": "off",
    },
    linterOptions: { reportUnusedDisableDirectives: "off" },
  },
];
